// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-worlds.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/data.ts
var WORLDS = [
  {
    slug: "sakura",
    name: "Sakura",
    tag: "Bloom",
    tagline: "Un printemps \xE9ternel, suspendu au cr\xE9puscule.",
    description: "P\xE9tales de cerisier d\xE9rivant en 360\xB0, lanternes papier et un ciel rose-p\xEAche. L'univers le plus contemplatif de YUME.",
    color: "#F25BB5",
    ambience: ["P\xE9tales en suspension", "Lanternes ambr\xE9es", "Brise ti\xE8de"],
    sound: "Koto \xB7 field-recording de Kyoto au printemps",
    pairing: "Matcha latte sakura \xB7 Souffl\xE9 pancake fleur de cerisier"
  },
  {
    slug: "tokyo-neon",
    name: "Tokyo Neon",
    tag: "Pulse",
    tagline: "Shibuya sous la pluie, \xE0 3 heures du matin.",
    description: "N\xE9ons satur\xE9s, katakana en mouvement, reflets mouill\xE9s sur l'asphalte. L'\xE9nergie d'une nuit qui ne dort pas.",
    color: "#7C3AED",
    ambience: ["Pluie n\xE9on", "Enseignes pulsantes", "Foules lointaines"],
    sound: "City-pop \xB7 synthwave japonais 80s",
    pairing: "Yuzu electric tonic \xB7 Maki signature du chef"
  },
  {
    slug: "zen-forest",
    name: "Zen Forest",
    tag: "Breath",
    tagline: "La for\xEAt de bambous, juste apr\xE8s l'orage.",
    description: "Brume, mousse, troncs verticaux \xE0 perte de vue. Un sas de d\xE9c\xE9l\xE9ration pour respirer plus lentement.",
    color: "#34D27B",
    ambience: ["Brume rasante", "Bambous oscillants", "Eau qui coule"],
    sound: "Shakuhachi \xB7 pluie sur feuillage",
    pairing: "Matcha c\xE9r\xE9monie \xB7 Mochi yuzu-th\xE9 vert"
  },
  {
    slug: "aquarium",
    name: "Aquarium",
    tag: "Drift",
    tagline: "Immerg\xE9 parmi les m\xE9duses bioluminescentes.",
    description: "Le sol dispara\xEEt, les murs deviennent oc\xE9an. Une d\xE9rive lente entre coraux et cr\xE9atures de lumi\xE8re.",
    color: "#4DD0E1",
    ambience: ["Bioluminescence", "Courants 360\xB0", "Reflets aquatiques"],
    sound: "Drones sous-marins \xB7 chants de baleines lointains",
    pairing: "Blue ocean lemonade \xB7 Cr\xEApe br\xFBl\xE9e vanille-yuzu"
  },
  {
    slug: "kyoto",
    name: "Kyoto",
    tag: "Heritage",
    tagline: "Une c\xE9r\xE9monie du th\xE9 dans un temple oubli\xE9.",
    description: "Bois patin\xE9, dorures discr\xE8tes, fusuma peints \xE0 la main. L'\xE2me du Japon traditionnel, recompos\xE9e en pixels.",
    color: "#FFC24B",
    ambience: ["Lanternes de papier", "Bois sombre", "Jardin sec"],
    sound: "Cordes de shamisen \xB7 gong de temple",
    pairing: "Hojicha latte \xB7 Wagashi du jour"
  },
  {
    slug: "galaxy",
    name: "Galaxy",
    tag: "Infinity",
    tagline: "Un voyage immobile au c\u0153ur d'une n\xE9buleuse.",
    description: "\xC9toiles \xE0 360\xB0, nuages cosmiques, station orbitale. Le plus cin\xE9matographique des six mondes.",
    color: "#A78BFA",
    ambience: ["Champ stellaire", "N\xE9buleuses lentes", "Apesanteur visuelle"],
    sound: "Drones ambient \xB7 synth\xE9s Vangelis",
    pairing: "Cosmic violet matcha \xB7 Souffl\xE9 pancake galaxy"
  }
];
var MENU = [
  { slug: "matcha-latte", name: "Matcha Latte", category: "Boissons chaudes", description: "Matcha c\xE9r\xE9monie fouett\xE9, lait micro-mousse.", price_dt: 14 },
  { slug: "hojicha-latte", name: "Hojicha Latte", category: "Boissons chaudes", description: "Th\xE9 vert torr\xE9fi\xE9, notes caramel-noisette.", price_dt: 14 },
  { slug: "matcha-espresso", name: "Matcha Espresso Fusion", category: "Boissons chaudes", description: "Double shot + matcha, \xE9nergie signature.", price_dt: 16 },
  { slug: "specialty-coffee", name: "Specialty Coffee", category: "Boissons chaudes", description: "Grains single-origin, extraction lente.", price_dt: 10 },
  { slug: "brown-sugar-boba", name: "Brown Sugar Boba", category: "Bubble tea", description: "Perles tapioca caram\xE9lis\xE9es, lait entier.", price_dt: 16 },
  { slug: "taro-bubble-tea", name: "Taro Bubble Tea", category: "Bubble tea", description: "Taro violet cr\xE9meux, perles noires.", price_dt: 16 },
  { slug: "strawberry-milk-tea", name: "Strawberry Milk Tea", category: "Bubble tea", description: "Fraises fra\xEEches, th\xE9 noir, lait.", price_dt: 16 },
  { slug: "sakura-lemonade", name: "Sakura Lemonade", category: "Mocktails", description: "Fleur de cerisier, citron, tonic.", price_dt: 15 },
  { slug: "yuzu-soda", name: "Yuzu Soda", category: "Mocktails", description: "Agrume japonais, eau p\xE9tillante.", price_dt: 13 },
  { slug: "matcha-mojito", name: "Matcha Mojito", category: "Mocktails", description: "Matcha, menthe, citron vert, sucre de canne.", price_dt: 17 },
  { slug: "lychee-yuzu-sparkler", name: "Lychee Yuzu Sparkler", category: "Mocktails", description: "Litchi, yuzu, bulles fines.", price_dt: 17 },
  { slug: "virgin-tokyo-mule", name: "Virgin Tokyo Mule", category: "Mocktails", description: "Gingembre, citron vert, ginger beer.", price_dt: 17 },
  { slug: "neon-sakuraglow", name: "Neon Sakura Glow", category: "Mocktails", description: "Signature \u2014 sirop sakura, tonic bleu, luminescence.", price_dt: 19 },
  { slug: "nigiri-salmon", name: "Nigiri Saumon", category: "Sushi & Maki", description: "Riz vinaigr\xE9, saumon frais tranch\xE9.", price_dt: 12 },
  { slug: "california-roll", name: "California Roll", category: "Sushi & Maki", description: "Crabe, avocat, concombre, s\xE9same.", price_dt: 22 },
  { slug: "spicy-tuna-roll", name: "Spicy Tuna Roll", category: "Sushi & Maki", description: "Thon, sauce \xE9pic\xE9e signature.", price_dt: 24 },
  { slug: "dragon-roll", name: "Dragon Roll", category: "Sushi & Maki", description: "Anguille, avocat, sauce teriyaki.", price_dt: 28 },
  { slug: "ebi-tempura-roll", name: "Ebi Tempura Roll", category: "Sushi & Maki", description: "Crevette tempura croustillante.", price_dt: 24 },
  { slug: "vegetarian-roll", name: "Vegetarian Roll", category: "Sushi & Maki", description: "Avocat, concombre, mangue, radis.", price_dt: 18 },
  { slug: "souffle-pancake", name: "Souffl\xE9 Pancake", category: "Desserts", description: "Pancakes japonais nuageux, fruits de saison.", price_dt: 22 },
  { slug: "mochi", name: "Mochi Assortis", category: "Desserts", description: "Trio de mochis artisanaux.", price_dt: 15 },
  { slug: "mochi-gelato", name: "Mochi Gelato", category: "Desserts", description: "Glace enrob\xE9e de p\xE2te de riz.", price_dt: 16 },
  { slug: "dorayaki", name: "Dorayaki", category: "Desserts", description: "Pancake fourr\xE9 \xE0 la p\xE2te d'azuki.", price_dt: 12 },
  { slug: "taiyaki", name: "Taiyaki", category: "Desserts", description: "Gaufre poisson, garniture matcha ou chocolat.", price_dt: 14 },
  { slug: "matcha-cheesecake", name: "Matcha Cheesecake", category: "Desserts", description: "Cheesecake japonais matcha c\xE9r\xE9monie.", price_dt: 18 },
  { slug: "brule-crepe", name: "Br\xFBl\xE9e Cr\xEApe", category: "Desserts", description: "Cr\xEApe vanille caram\xE9lis\xE9e au chalumeau.", price_dt: 17 },
  { slug: "lava-cake", name: "Lava Cake", category: "Desserts", description: "Fondant chocolat noir, c\u0153ur coulant.", price_dt: 18 }
];
var VENUE = {
  name: "YUME Caf\xE9 \xB7 Lounge",
  meaning: "\u5922 \u2014 \xAB r\xEAve \xBB en japonais",
  city: "Sousse, Tunisia",
  concept: "Caf\xE9-lounge immersif alcohol-free. 6 mondes LED th\xE9matiques (Sakura, Tokyo Neon, Zen Forest, Aquarium, Kyoto, Galaxy). Cuisine japonaise moderne, matcha c\xE9r\xE9monie, mocktails signature.",
  language: "Fran\xE7ais",
  hours: "12:00 \u2013 00:00 tous les jours",
  reservation_url: "https://yume-tn.lovable.app/#reservation"
};

// src/lib/mcp/cache.ts
var store = /* @__PURE__ */ new Map();
var DEFAULT_TTL_MS = 5 * 60 * 1e3;
var MAX_ENTRIES = 200;
function memoize(key, compute, ttlMs = DEFAULT_TTL_MS) {
  const now = Date.now();
  const hit = store.get(key);
  if (hit && hit.expiresAt > now) return hit.value;
  const value = compute();
  if (store.size >= MAX_ENTRIES) {
    const firstKey = store.keys().next().value;
    if (firstKey !== void 0) store.delete(firstKey);
  }
  store.set(key, { value, expiresAt: now + ttlMs });
  return value;
}
function cacheKey(tool, input) {
  if (!input) return tool;
  const normalized = {};
  for (const k of Object.keys(input).sort()) {
    const v = input[k];
    normalized[k] = typeof v === "string" ? v.trim().toLowerCase() : v;
  }
  return `${tool}:${JSON.stringify(normalized)}`;
}

// src/lib/mcp/tools/list-worlds.ts
var list_worlds_default = defineTool({
  name: "list_worlds",
  title: "List immersive worlds",
  description: "List every themed immersive world (LED universe) available at YUME Caf\xE9 \xB7 Lounge in Sousse, Tunisia. Returns slug, name, tagline and accent color for each world.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    return memoize(cacheKey("list_worlds"), () => {
      const summary = WORLDS.map((w) => ({
        slug: w.slug,
        name: w.name,
        tag: w.tag,
        tagline: w.tagline,
        color: w.color
      }));
      return {
        content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
        structuredContent: { worlds: summary }
      };
    });
  }
});

// src/lib/mcp/tools/get-world.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var get_world_default = defineTool2({
  name: "get_world",
  title: "Get world details",
  description: "Return the full description of one immersive YUME world \u2014 its atmosphere, soundtrack and recommended food & drink pairing.",
  inputSchema: {
    slug: z.string().min(1).describe("World slug. One of: sakura, tokyo-neon, zen-forest, aquarium, kyoto, galaxy.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const normalized = slug.trim().toLowerCase();
    return memoize(cacheKey("get_world", { slug: normalized }), () => {
      const world = WORLDS.find((w) => w.slug === normalized);
      if (!world) {
        return {
          content: [
            {
              type: "text",
              text: `No world with slug "${slug}". Available: ${WORLDS.map((w) => w.slug).join(", ")}.`
            }
          ],
          isError: true
        };
      }
      return {
        content: [{ type: "text", text: JSON.stringify(world, null, 2) }],
        structuredContent: { world }
      };
    });
  }
});

// src/lib/mcp/tools/search-menu.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var CATEGORIES = Array.from(new Set(MENU.map((m) => m.category)));
var search_menu_default = defineTool3({
  name: "search_menu",
  title: "Search the menu",
  description: "Search the YUME menu (drinks, sushi, desserts). Optionally filter by category or a free-text query matched against name and description. Prices are in Tunisian Dinar (DT).",
  inputSchema: {
    query: z2.string().trim().optional().describe('Free-text keyword, e.g. "matcha" or "vegan".'),
    category: z2.string().trim().optional().describe(`Optional category filter. One of: ${CATEGORIES.join(", ")}.`)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query, category }) => {
    return memoize(cacheKey("search_menu", { query, category }), () => {
      const q = query?.toLowerCase();
      const cat = category?.toLowerCase();
      const items = MENU.filter((m) => {
        if (cat && m.category.toLowerCase() !== cat) return false;
        if (q && !`${m.name} ${m.description}`.toLowerCase().includes(q)) return false;
        return true;
      });
      return {
        content: [
          {
            type: "text",
            text: items.length ? JSON.stringify(items, null, 2) : "No menu items match those filters."
          }
        ],
        structuredContent: { count: items.length, categories: CATEGORIES, items }
      };
    });
  }
});

// src/lib/mcp/tools/venue-info.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
var venue_info_default = defineTool4({
  name: "venue_info",
  title: "Venue info",
  description: "Return general information about YUME Caf\xE9 \xB7 Lounge in Sousse, Tunisia: concept, opening hours, reservation link and the list of themed worlds.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    return memoize(cacheKey("venue_info"), () => {
      const payload = { ...VENUE, worlds: WORLDS.map((w) => ({ slug: w.slug, name: w.name })) };
      return {
        content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
        structuredContent: payload
      };
    });
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "yume-mcp",
  title: "YUME Caf\xE9 \xB7 Lounge",
  version: "0.1.0",
  instructions: "Tools for YUME Caf\xE9 \xB7 Lounge (Sousse, Tunisia). Use `venue_info` for concept, hours and reservation link, `list_worlds` / `get_world` to explore the 6 immersive LED worlds (Sakura, Tokyo Neon, Zen Forest, Aquarium, Kyoto, Galaxy), and `search_menu` to browse drinks, sushi and desserts (prices in DT).",
  tools: [venue_info_default, list_worlds_default, get_world_default, search_menu_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
